env:
  matrix:
  - VERSION=0.0.1
  global:
    secure: SERHSsFvt7ChSYYaYUVS15alO3IK/Z+D0dO7bXCznkYRVSWpbcWi96goXvEvxowVhh/SgAaN39/LOoQ25UjK8fiLTZ66ZLTOJ/hGGKVA06hdqbl/hOVT8YlGPEPpzHhaD1EJi5KHJlOaQYYLi7NZos5B1mqYLrV4yoFY86b+hNCy/vStONymIYepfnUv/XrVgiEGyFHI5fYUUYA0duSu2CYdosZC1S+jo0M+UssODw7Wc80aipkOfCd2qJr4QmYDvoeAXtgPksyfCCcDhRYfc8/aMepWcBQoYvApE2vaUg9AL9/n7AjLW2KdCpDogqkkcR/1hUqpD6E00LdpvVkaXeAgnbtOVJTDCZhb2YNMwgp5NPvgPezKq5IhHLUsO2yPiSiHaCQs03iDCcTqrnbahEj8BS3yW6ty6DpzEFPZ7T+efLFluRMFOD+4h1JMGFAdJNYOeFm1lD9sYkNYn7adMxdpQJ6tcx1GtSIbyUbKBgoD+pTEBi6WgtiHt2PkLxmfKiGv44r+YTpRPQ38Sibhi1VLdCQyCjVegFllc+q3L7/hEp8ISFx7+FFJNixNDllx9EqYaKY3xWtyf9ktEYAsPoe4aIUoyB1ORADz/b2mfbM+flRrrgHD30QXrOQMTHRwkLj+lWseqUS+sYrsMptbmbcVx8B+8T6s0dPtnoWOhh8=

services:
- docker

script:
- docker build --build-arg VERSION="${VERSION}" -t temp-build .
- docker run --rm temp-build --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
